### ISSUE TITLE
Lower PHP version support

### ISSUE THREAD

**Issue by ZBrettonYe** [rawilk/laravel-settings#1]
Love the idea of this package. 

Cloud this package require lower PHP version? since the Laravel official framework 7.x PHP version minimum requirement  is 7.2.5

**Comment by rawilk** [comment]
Thanks for your interest in this package. Since I use php 7.4 syntax in the package, such as specifying types for class properties, and using arrow functions (`fn () => `), it is not possible to lower the minimum php version. 

I personally only use php 7.4, which is why I write my packages using the available language syntax. I see no reason why you wouldn't upgrade your php versions, but I do understand there may be cases where you are limited by your hosting provider or something like that.

**Comment by rawilk** [comment]
Btw, you are more than welcome to fork and maintain your own version that is compatible with php 7.2 or whatever version you need. Just be sure to include the original license in the repo.

**Comment by ZBrettonYe** [comment]
Thanks for your speedy respond 👍 

I will upgrade my PHP environment to 7.4 for this package, since I will upgrade it one day anyway
