### ISSUE TITLE
[Feature Request]: Migrations do not support teams using UUIDs or ULIDs

### ISSUE THREAD

**Issue by assemblerdigital** [rawilk/laravel-settings#50]
### Feature Description

Pretty straight forward, I just altered the add_settings_team_field migration file and it was fine, I'm not sure this is worth writing actual code for, but it might warrant a note in the documentation?

**Comment by rawilk** [comment]
You are free to modify the published stub to have the desired database structure to handle your application's requirements. The migrations in this package, like many other packages out there, default to integer ids since that's usually what is used in a typical application. 

I may modify the docs so it's clear you are able to use uuids or ulids on the table if you need to.

**Comment by rawilk** [comment]
I'm going to close this issue since it hasn't had any activity for a while. Feel free to re-open in the future if necessary.
